import { OnInit, EventEmitter } from '@angular/core';
import { Observable } from 'rxjs/Rx';
import { ControlValueAccessor } from '@angular/forms';
export declare class ComboBoxComponent implements ControlValueAccessor, OnInit {
    displayField: string;
    valueField: string;
    remote: boolean;
    clearOnSelect: boolean;
    forceSelection: boolean;
    localFilter: boolean;
    typeAheadDelay: number;
    inputClass: string;
    loadingIconClass: string;
    triggerIconClass: string;
    dataRoot: string;
    disabledField: string;
    onQuery: EventEmitter<string>;
    onSelect: EventEmitter<string>;
    onCreate: EventEmitter<string>;
    onBlur: EventEmitter<any>;
    onInitValue: EventEmitter<string>;
    loading: boolean;
    hideList: boolean;
    data: any[];
    private _listDataSubscription;
    private _aheadTimer;
    private _currVal;
    private _marked;
    private _initialData;
    private _hasFocus;
    private _tmpVal;
    private propagateTouch;
    private propagateChange;
    constructor();
    ngOnInit(): void;
    listData: Observable<Object[]> | Object[];
    currVal: string;
    marked: number;
    onKeyDown(event: KeyboardEvent): void;
    onItemClick(index: number, item: Object): void;
    onFieldBlur(event: FocusEvent): void;
    onFieldFocus(): void;
    isMarked(value: Object): boolean;
    isDisabled(value: Object): boolean;
    private handleEnter();
    private handleUp();
    private handleDown();
    private clear();
    private getDisplayValue(val);
    private getValueValue(val);
    private loadData();
    private sendModelChange(val);
    private searchValueObject(value);
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
}
